locations:
  - name: kansas_city
    latitude: 39.0997
    longitude: -94.5786
    timezone: America/Chicago

  - name: chicago
    latitude: 41.8781
    longitude: -87.6298
    timezone: America/Chicago